name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake -DBUILD_TESTS=OFF ..
    - name: make
      run: cmake --build build
    - name: action-gtest
      uses: CyberZHG/github-action-gtest@0.0.1
      with:
        runs: "cd build && cmake .. && make && cd tests && make && ./test_basic_primitives"
